### PR TITLE
simplify examples

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

since we do not run tests on examples anyway there is o reason to have them wrap in main especially since there is nothing else than main anyway...

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-lash/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by carmocca** [comment]
I believe the examples hang with `num_workers > 0` on some platforms (namely MacOS) if this is removed

**Comment by Borda** [comment]
> I believe the examples hang with `num_workers > 0` on some platforms (namely MacOS) if this is removed

not really, they are not even called anywhere :D
https://github.com/PyTorchLightning/lightning-flash/blob/3c5b535ce26a12fd141acff7e20bc2b18ee56a0a/.github/workflows/ci-testing.yml#L80

**Comment by carmocca** [comment]
We do test some of them:

https://github.com/PyTorchLightning/lightning-flash/blob/master/tests/examples/test_examples.py

Also `num_workers` is currently set to 0 by default

https://github.com/PyTorchLightning/lightning-flash/blob/3c5b535ce26a12fd141acff7e20bc2b18ee56a0a/flash/core/data/datamodule.py#L67-L73

**Comment by Borda** [comment]
> We do test some of them:

yes but here you test just some of them and the execution is called from tests folder
the wrap in if/main is typical if you want to call test on `flash_examples` as a folder and skip some code...
which is not the case, right?

**Comment by teddykoker** [comment]
if/main is needed in order for the dataloaders to function properly (because of multiprocessing)

**Comment by Borda** [comment]
> if/main is needed in order for the dataloaders to function properly (because of multiprocessing)

so the script is called in a subprocess, but it does not have if/main it is empty so when/how it is called?
but here all tests are passing so what test are/were hanging?

**Comment by carmocca** [comment]
As I said, try uncommenting

https://github.com/PyTorchLightning/lightning-flash/blob/3c5b535ce26a12fd141acff7e20bc2b18ee56a0a/flash/core/data/datamodule.py#L67-L73

And let's see if CI passes

**Comment by Borda** [comment]
> As I said, try uncommenting

trying now, but as it is, you preventing the hanging n two fronts - in examples and restricting workers to 0

**Comment by Borda** [comment]
@carmocca seems to be fine, no hanging...

**Comment by carmocca** [comment]
The failing MacOS tests seem to show otherwise 😆

**Comment by Borda** [comment]
> > As I said, try uncommenting
> 
> trying now, but as it is, you preventing the hanging n two fronts - in examples and restricting workers to 0

@carmocca ^^

**Comment by carmocca** [comment]
I'm not sure about what are you trying to say.

But you just removed both fronts.

And in any case, we cant fix num_workers 0 forever. So that's why the examples require `if __name__: __main__`

**Comment by Borda** [comment]
> But you just removed both fronts.

Because you asked for it, so I am returning to workers count 0

**Review by tchaton — APPROVED** [review]

**Pull request merged**
