### PR TITLE
support list & callable transforms

### LINKED ISSUE #644: Support for a list of transforms rather than dict
## 🚀 Feature

Enable support for just a list of transforms / a single Sequential or Compose transform to be passed to the preprocess. This could just be bound to the `pre_tensor_transform` hook by default.

### PR DESCRIPTION
**Pull request by aniketmaurya**
## What does this PR do?

Fixes #644 

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-flash/tree/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by aniketmaurya** [comment]
`deepsource` check has been running since a day 🤔

**Comment by akihironitta** [comment]
> `deepsource` check has been running for a day

It seems the check was done in a minute, but the status of the run hasn't been updated on GitHub somehow...

**Comment by aniketmaurya** [comment]
> > `deepsource` check has been running for a day
> 
> It seems the check was done in a minute, but the status of the run hasn't been updated on GitHub somehow...

@ethanwharris could you rerun that check?

**Review by ethanwharris — APPROVED** [review]
LGTM :smiley:

**Pull request merged**
