### PR TITLE
Factored out ROGUE and BLEU metrics

### LINKED ISSUE #538: Factor out our current Rouge and BLEU metrics to flash/text/seq2seq/metrics.py

### PR DESCRIPTION
**Pull request by karthikrangasai**
## What does this PR do?

Fixes #538 

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-flash/tree/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by ethanwharris — APPROVED** [review]
Awesome! LGTM :smiley:

**Comment by karthikrangasai** [comment]
@ethanwharris 

How do I edit documents references ? I'm not sure the documentation system works.

Also, can I work on the QuestionAnswering Task-a-thon series ?

**Comment by ethanwharris** [comment]
Hi @karthikrangasai it looks like the errors are in this file:
https://github.com/PyTorchLightning/lightning-flash/blob/72f5a9e5ea90eb4713389ebe675a29b7ba58d429/docs/source/code/text.rst
Just need to change the metric references to point to the new files.

It's no problem for you to switch to question answering if you prefer, nothing is set in stone :smiley:

**Comment by karthikrangasai** [comment]
I have updated the corresponding file but the docs check fails with two more warnings.
I am not sure how to tackle the error.

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by ethanwharris** [comment]
Hi @karthikrangasai, I've resolved the docs build for you, the error was caused by using `automodule` with a reference to a class (for which you would use `autoclass` I think). This is ready to go!

**Comment by karthikrangasai** [comment]
@ethanwharris 
Thank you. I didn't know the difference as I'm still learning sphinx.

**Comment by ethanwharris** [comment]
@karthikrangasai That's no problem :smiley: Sphinx is a pain haha

**Pull request merged**
