### PR TITLE
Run tests on GPUs nightly only

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
cc @Borda

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-flash/tree/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [n/a] Did you write any new necessary tests? [not needed for typos/docs]
- [n/a] Did you verify new and existing tests pass locally with your changes?
- [n/a] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by akihironitta** [comment]
The failing test should be addressed in #334.
```
FAILED tests/examples/test_scripts.py::test_example[predict-translation.py]
```

**Review by Borda — APPROVED** [review]

**Review by edgarriba — APPROVED** [review]

**Review by ethanwharris — CHANGES_REQUESTED** [review]
We had this at one point before and the GPU tests continued to run on every branch but it also caused the coverage tracking to break as it thought every GPU coverage report was on the master branch. Don't know what was causing that, but this still seems to be running GPU tests on this branch, so I'm not sure it's doing what we want...

**Comment by edgarriba** [comment]
@akihironitta @Borda @ethanwharris we have a similar setup in kornia that could help: https://github.com/kornia/kornia/blob/master/.github/workflows/tests_cpu_versions.yml#L3-L9

**Comment by akihironitta** [comment]
@ethanwharris Thank you for your investigation! I just turned them off with the following lines.
```
trigger: none
pr: none
```

**Comment by akihironitta** [comment]
@ethanwharris Thank you for your investigation! I just turned them off with the following lines.
```
trigger: none
pr: none
```

**Review by justusschock — APPROVED** [review]

**Review by ethanwharris — APPROVED** [review]
Awesome, LGTM :smiley:

**Comment by Borda** [comment]
> @akihironitta @Borda @ethanwharris we have a similar setup in kornia that could help: https://github.com/kornia/kornia/blob/master/.github/workflows/tests_cpu_versions.yml#L3-L9

yes but you use GHA and this is Azure pipelines so the syntax and behaviour is a bit different...

**Comment by Borda** [comment]
@ethanwharris just thinking we shall keep triggers for tags so can use the badge in pypi... what do you think?
cc: @akihironitta

**Comment by ethanwharris** [comment]
@Borda Yeah, that seems reasonable, we should probably run all tests on releases :smiley:

**Pull request merged**
