### PR TITLE
change Module not found error to a more verbose pip install command

### PR DESCRIPTION
**Pull request by deepseek-eoghan**
## What does this PR do?

Change if not _IMAGE_AVAILABLE: ModuleNotFoundError message in flash.image.detection.model.py line 97.

From: ``` raise ModuleNotFoundError("Please, pip install . [image]") ``` 
To:     ``` raise ModuleNotFoundError("Please, pip install lightning-flash[image]") ```

Fixes # (issue)

## Before submitting
- [X] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [X] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-flash/tree/master/.github/CONTRIBUTING.md), Pull Request section?
- [X] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes?
- [X] Did you write any new necessary tests? [not needed for typos/docs]
- [X] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)?

## PR review
 - [X] Is this pull request ready for review? (if not, please submit in draft mode)

### CODE REVIEW

**Comment by akihironitta** [comment]
@deepseek-eoghan Thank you for submitting this PR! LGTM! Could you also update all occurrences in the codebase?

```console
$ grep -rn "pip install" flash
flash/tabular/classification/model.py:60:            raise ModuleNotFoundError("Please, pip install -e '.[tabular]'")
flash/video/classification/data.py:137:            raise ModuleNotFoundError("Please, run `pip install pytorchvideo`.")
flash/image/style_transfer/model.py:97:            raise ModuleNotFoundError("Please, pip install -e '.[image_style_transfer]'")
flash/image/segmentation/model.py:89:            raise ModuleNotFoundError("Please, pip install -e '.[image]'")
flash/image/segmentation/data.py:83:            raise ModuleNotFoundError("Please, pip install -e '.[image]'")
flash/image/segmentation/data.py:175:            raise ModuleNotFoundError("Please, pip install -e '.[image]'")
flash/image/segmentation/data.py:404:            raise MisconfigurationException("You need matplotlib to visualise. Please, pip install matplotlib")
flash/image/embedding/model.py:63:            raise ModuleNotFoundError("Please, pip install -e '.[image]'")
flash/image/detection/model.py:97:            raise ModuleNotFoundError("Please, pip install . '[image]'")
flash/image/classification/data.py:120:            raise MisconfigurationException("You need matplotlib to visualise. Please, pip install matplotlib")
flash/text/seq2seq/core/model.py:69:            raise ModuleNotFoundError("Please, pip install -e '.[text]'")
flash/text/seq2seq/core/data.py:46:            raise ModuleNotFoundError("Please, pip install -e '.[text]'")
flash/text/seq2seq/core/data.py:193:            raise ModuleNotFoundError("Please, pip install -e '.[text]'")
flash/text/seq2seq/summarization/utils.py:27:    assert nltk, "nltk must be installed to separate newlines between sentences. (pip install nltk)"
flash/text/seq2seq/summarization/data.py:30:            raise ModuleNotFoundError("Please, pip install -e '.[text]'")
flash/text/seq2seq/summarization/metric.py:63:            raise ModuleNotFoundError("Please, pip install -e '.[text]'")
flash/text/classification/model.py:53:            raise ModuleNotFoundError("Please, pip install -e '.[text]'")
flash/text/classification/data.py:39:            raise ModuleNotFoundError("Please, pip install -e '.[text]'")
flash/text/classification/data.py:160:            raise ModuleNotFoundError("Please, pip install -e '.[text]'")
```

**Review by edgarriba — APPROVED** [review]

**Comment by deepseek-eoghan** [comment]
I've updated those listed above @akihironitta can the -e flag be removed from ``` pip install -e x ``` is there a reason for installing in editable mode?

**Review by ethanwharris — COMMENTED** [review]
Nice work @deepseek-eoghan :smiley: Yeah, you can drop the `-e` too. You'd only use it when installing for dev purposes.

**Review by akihironitta — APPROVED** [review]
@deepseek-eoghan LGTM!

**Review by ethanwharris — APPROVED** [review]
LGTM :smiley:

**Pull request merged**
