### PR TITLE
pin TV version

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?

need to pin TorchVision version as some internal dependencies broke as TV moved/renamed `utils`

Fixes:
```
    from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'
```

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-flash/tree/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by justusschock — CHANGES_REQUESTED** [review]
I haven't found this anywhere in our codebase. Also this is just an import from torch that shifted. So with the following we should be good to go without this restriction:

```
try:
    from torch.hub import load_state_dict_from_url  # noqa: 401
except ImportError:
    from torch.utils.model_zoo import load_url as load_state_dict_from_url  # noqa: 401
```

**Comment by Borda** [comment]
> I haven't found this anywhere in our codebase. Also this is just an import from torch that shifted.

no it is not in our codebase, but in our dependencies, IceVision >> TIMM

**Comment by justusschock** [comment]
then maybe we should just open an issue there? :)

**Comment by Borda** [comment]
@ethanwharris thoughts?

**Review by ethanwharris — CHANGES_REQUESTED** [review]
@Borda I'm not sure we shoyuld do this, all of our tests are passing so it's not clear what this is solving. Also, since each torchvision version is pinned to a specific torch version this would be equivalent to pinning `torch < 1.10` which is quite extreme

**Pull request closed without merging**
