### PR TITLE
[RFC] ci: Add direct link to generated docs

### PR DESCRIPTION
**Pull request by akihironitta**
## What does this PR do?
This PR adds a direct link to the doc artifacts with https://github.com/larsoner/circleci-artifacts-redirector-action.

There are quite a number of projects that use this GHA as I searched: https://github.com/search?q=larsoner%2Fcircleci-artifacts-redirector-action&type=code.

## Before submitting
- [RFC] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-flash/tree/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [n/a] Did you write any new necessary tests? [not needed for typos/docs]
- [n/a] Did you verify new and existing tests pass locally with your changes?
- [n/a] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-flash/blob/master/CHANGELOG.md)?

## PR review
 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
Looks empty now...

**Comment by akihironitta** [comment]
Blocked by https://github.com/PyTorchLightning/pytorch-lightning/issues/7455

**Comment by akihironitta** [comment]
The GHA doc says this action will be enabled once it gets merged into master:
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.

https://docs.github.com/en/actions/reference/events-that-trigger-workflows#status

**Review by ethanwharris — APPROVED** [review]
LGTM :smiley:

**Comment by akihironitta** [comment]
For information, we can now directly access the build docs from here :)

**Pull request merged**
